# Generated by Django 4.1.3 on 2023-01-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('shooter', models.IntegerField()),
                ('rpg', models.IntegerField()),
                ('story', models.IntegerField()),
                ('gloominess', models.IntegerField()),
                ('aesthetics', models.IntegerField()),
                ('survival', models.IntegerField()),
                ('fullness_of_world', models.IntegerField()),
                ('creative_potential', models.IntegerField()),
                ('fighting_system', models.IntegerField()),
                ('puzzles', models.IntegerField()),
                ('quests', models.IntegerField()),
                ('hardness', models.IntegerField()),
                ('complexity', models.IntegerField()),
                ('moral', models.IntegerField()),
                ('horror', models.IntegerField()),
                ('action', models.IntegerField()),
                ('emotionality', models.IntegerField()),
                ('reality', models.IntegerField()),
                ('atmosphere', models.IntegerField()),
                ('cover', models.IntegerField(null=True, unique=True)),
            ],
        ),
    ]
