# Generated by Django 4.1.3 on 2023-01-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamepredictor', '0002_rename_complexity_games_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='cover',
            field=models.ImageField(null=True, unique=True, upload_to=''),
        ),
    ]
