# Generated by Django 4.1.3 on 2023-01-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamepredictor', '0003_alter_games_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={'ordering': ['id'], 'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AlterField(
            model_name='games',
            name='cover',
            field=models.ImageField(null=True, unique=True, upload_to='', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='games',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название игры'),
        ),
    ]
