# Generated by Django 4.1.3 on 2023-01-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamepredictor', '0004_alter_games_options_alter_games_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='cover',
            field=models.ImageField(null=True, upload_to='', verbose_name='Обложка'),
        ),
    ]
